#!/usr/bin/env tsx
/**
 * Visual Generation Pipeline — end-to-end test harness.
 *
 * Every ContentItem is generated by the REAL content-gen LLM from
 * (lessonNumber, strategy) pairs — nothing is hand-written. Each phase reads
 * the prior phase's fixture from disk.
 *
 *   tsx scripts/test-pipeline.ts content   # Phase 0: lesson+strategy → real ContentItem
 *   tsx scripts/test-pipeline.ts scenes    # Phase A: ContentItem → SceneDescription
 *   tsx scripts/test-pipeline.ts stage2    # Phase B: SceneDescription → SVG/PNG (no API)
 *   tsx scripts/test-pipeline.ts stage3    # Phase C: SceneDescription + item → GPT-image
 *   tsx scripts/test-pipeline.ts full      # Phase D: orchestrator end-to-end
 */

import "dotenv/config";
import { config as loadEnv } from "dotenv";
import OpenAI from "openai";
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "fs";
import { join } from "path";

loadEnv({ path: ".env.local" });

import { generateContentItem } from "../lib/content-generator";
import type { ContentItem } from "../lib/types";
import { describeScene } from "../lib/visual-pipeline/scene-describer";
import { computeLayout } from "../lib/visual-pipeline/layout-engine";
import { buildSvg, rasterizeSvg } from "../lib/visual-pipeline/svg-builder";
import { generateFromSvg } from "../lib/visual-pipeline/image-generator";
import { runVisualPipeline } from "../lib/visual-pipeline/orchestrator";
import type { SceneDescription } from "../lib/visual-pipeline/types";

// ----------------------------------------------------------------------------
// Test cases — only seeds (lesson + strategy). Everything downstream comes
// from real LLM calls.
// ----------------------------------------------------------------------------

type TestCase = { key: string; lesson: number; strategy: string };

const TEST_CASES: TestCase[] = [
  { key: "caseA", lesson: 6, strategy: "analogy" },            // Newton's 3rd law
  { key: "caseB", lesson: 1, strategy: "cognitive conflict" }, // collision intro
  { key: "caseC", lesson: 3, strategy: "experience bridging" },// deformation
  { key: "caseD", lesson: 8, strategy: "engaged critiquing" }, // system models
];

// ----------------------------------------------------------------------------
// Paths
// ----------------------------------------------------------------------------

const OUT_ROOT = "output/pipeline-test";
const FIXTURES_DIR = join(OUT_ROOT, "fixtures");
const STAGE2_DIR = join(OUT_ROOT, "stage2");
const STAGE3_DIR = join(OUT_ROOT, "stage3");
const FULL_DIR = join(OUT_ROOT, "full");

const ensureDir = (p: string) => mkdirSync(p, { recursive: true });

const itemPath = (key: string) => join(FIXTURES_DIR, `item_${key}.json`);
const scenePath = (key: string) => join(FIXTURES_DIR, `scene_${key}.json`);

const dataUrlToBuffer = (dataUrl: string): Buffer => {
  const base64 = dataUrl.split(",")[1];
  return Buffer.from(base64, "base64");
};

const loadJson = <T>(path: string, hint: string): T => {
  if (!existsSync(path)) {
    throw new Error(`Missing fixture: ${path}. Run '${hint}' first.`);
  }
  return JSON.parse(readFileSync(path, "utf-8")) as T;
};

// ----------------------------------------------------------------------------
// Phase 0 — generate real ContentItems from (lesson, strategy) seeds
// ----------------------------------------------------------------------------

const runContent = async (client: OpenAI) => {
  ensureDir(FIXTURES_DIR);
  for (const { key, lesson, strategy } of TEST_CASES) {
    console.log(`[content] ${key}: lesson=${lesson} strategy=${strategy} — calling content-gen LLM...`);
    const item = await generateContentItem(client, lesson, strategy);
    const withId: ContentItem = { ...item, id: key };
    writeFileSync(itemPath(key), JSON.stringify(withId, null, 2));
    const wordCount = item.body.split(/\s+/).length;
    console.log(`           → title="${item.title}" body=${wordCount}w visualBrief=${item.visualBrief ? '"' + item.visualBrief.slice(0, 60) + '..."' : "(none)"}`);
  }
  console.log(`\n[content] Done. Fixtures in ${FIXTURES_DIR}/`);
};

// ----------------------------------------------------------------------------
// Phase A — generate real SceneDescription from each ContentItem
// ----------------------------------------------------------------------------

const runScenes = async (client: OpenAI) => {
  ensureDir(FIXTURES_DIR);
  for (const { key, lesson } of TEST_CASES) {
    const item = loadJson<ContentItem>(
      itemPath(key),
      "tsx scripts/test-pipeline.ts content",
    );
    console.log(`[scenes] ${key} — calling scene-describer LLM...`);
    const scene = await describeScene(client, item, lesson);
    writeFileSync(scenePath(key), JSON.stringify(scene, null, 2));
    console.log(`           → composition=${scene.composition} objects=${scene.objects.length} rels=${scene.relationships.length}`);
  }
  console.log(`\n[scenes] Done. Scene fixtures in ${FIXTURES_DIR}/`);
};

// ----------------------------------------------------------------------------
// Phase B — Stage 2 only (no API)
// ----------------------------------------------------------------------------

const runStage2 = async () => {
  ensureDir(STAGE2_DIR);
  for (const { key } of TEST_CASES) {
    const scene = loadJson<SceneDescription>(
      scenePath(key),
      "tsx scripts/test-pipeline.ts scenes",
    );
    const layout = computeLayout(scene);
    const svg = buildSvg(layout);
    const png = await rasterizeSvg(svg);

    writeFileSync(join(STAGE2_DIR, `scene_${key}.svg`), svg);
    writeFileSync(join(STAGE2_DIR, `scene_${key}.png`), png);

    console.log(
      `[stage2] ${key} composition=${scene.composition} objects=${layout.objects.length} rels=${layout.relationships.length} svg=${svg.length}B png=${png.length}B`,
    );
  }
  console.log(`\n[stage2] Done. Inspect ${STAGE2_DIR}/*.svg`);
};

// ----------------------------------------------------------------------------
// Phase C — Stage 2 + Stage 3 (GPT-image)
// ----------------------------------------------------------------------------

const runStage3 = async (client: OpenAI) => {
  ensureDir(STAGE3_DIR);
  for (const { key, lesson } of TEST_CASES) {
    const item = loadJson<ContentItem>(
      itemPath(key),
      "tsx scripts/test-pipeline.ts content",
    );
    const scene = loadJson<SceneDescription>(
      scenePath(key),
      "tsx scripts/test-pipeline.ts scenes",
    );

    console.log(`[stage3] ${key} — Stage 2 then GPT-image edit...`);
    const layout = computeLayout(scene);
    const svg = buildSvg(layout);
    const png = await rasterizeSvg(svg);
    writeFileSync(join(STAGE3_DIR, `scene_${key}_reference.png`), png);

    const finalDataUrl = await generateFromSvg(client, png, item, lesson);
    writeFileSync(join(STAGE3_DIR, `scene_${key}_final.webp`), dataUrlToBuffer(finalDataUrl));
    console.log(`           → reference.png + final.webp`);
  }
  console.log(`\n[stage3] Done. Compare ${STAGE3_DIR}/*_reference.png vs *_final.webp`);
};

// ----------------------------------------------------------------------------
// Phase D — full pipeline via orchestrator
// ----------------------------------------------------------------------------

const runFull = async (client: OpenAI) => {
  ensureDir(FULL_DIR);
  for (const { key, lesson, strategy } of TEST_CASES) {
    console.log(`[full] ${key}: lesson=${lesson} strategy=${strategy} — generating content then running full pipeline...`);

    // Fresh content (don't rely on fixture — this is a true end-to-end test).
    const item: ContentItem = {
      ...(await generateContentItem(client, lesson, strategy)),
      id: key,
    };
    writeFileSync(join(FULL_DIR, `${key}_item.json`), JSON.stringify(item, null, 2));

    const result = await runVisualPipeline(client, item, lesson);

    if (result.sceneDescription) {
      writeFileSync(
        join(FULL_DIR, `${key}_scene.json`),
        JSON.stringify(result.sceneDescription, null, 2),
      );
    }
    if (result.svgDataUrl) {
      const svg = Buffer.from(result.svgDataUrl.split(",")[1], "base64").toString("utf-8");
      writeFileSync(join(FULL_DIR, `${key}_layout.svg`), svg);
      const png = await rasterizeSvg(svg);
      writeFileSync(join(FULL_DIR, `${key}_reference.png`), png);
    }
    writeFileSync(join(FULL_DIR, `${key}_final.webp`), dataUrlToBuffer(result.url));

    console.log(
      `       done. usedFallback=${result.usedFallback} composition=${result.sceneDescription?.composition ?? "(fallback)"}`,
    );
  }
  console.log(`\n[full] Done. Full outputs in ${FULL_DIR}/`);
};

// ----------------------------------------------------------------------------
// Main
// ----------------------------------------------------------------------------

const main = async () => {
  const mode = process.argv[2] || "stage2";
  const needsApi = mode !== "stage2";

  if (needsApi && !process.env.OPENAI_API_KEY) {
    console.error(`OPENAI_API_KEY not set (required for mode: ${mode})`);
    process.exit(1);
  }

  const client = needsApi
    ? new OpenAI({ apiKey: process.env.OPENAI_API_KEY })
    : (null as unknown as OpenAI);

  switch (mode) {
    case "content":
      await runContent(client);
      break;
    case "scenes":
      await runScenes(client);
      break;
    case "stage2":
      await runStage2();
      break;
    case "stage3":
      await runStage3(client);
      break;
    case "full":
      await runFull(client);
      break;
    default:
      console.error(`Unknown mode: ${mode}. Use: content | scenes | stage2 | stage3 | full`);
      process.exit(1);
  }
};

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
